In [1]:
import numpy as np
import torch
import tensorflow as tf

In [2]:
np.random.seed(2024)
torch.manual_seed(2024)
tf.random.set_seed(2024)

# Câu 1

In [7]:
print(np.arange(0,10,1))

[0 1 2 3 4 5 6 7 8 9]


In [8]:
print(torch.arange(0,10,1))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [6]:
print(tf.range(0,10,1))

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


# Câu 2

In [10]:
print(np.eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
print(torch.eye(3,3))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [12]:
print(tf.eye(3,3))

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


# Câu 3

In [14]:
print(np.random.rand(3,4))

[[0.58801452 0.69910875 0.18815196 0.04380856]
 [0.20501895 0.10606287 0.72724014 0.67940052]
 [0.4738457  0.44829582 0.01910695 0.75259834]]


In [15]:
print(torch.rand(3,4))

tensor([[0.5317, 0.8313, 0.9718, 0.1193],
        [0.1669, 0.3495, 0.2150, 0.6201],
        [0.4849, 0.7492, 0.1521, 0.5625]])


In [17]:
print(tf.random.uniform(shape = (3,4), minval = 0, maxval = 1,dtype=tf.float32))

tf.Tensor(
[[0.90034294 0.19453335 0.36069036 0.66361904]
 [0.76605344 0.2159369  0.6261736  0.07380784]
 [0.22062695 0.934368   0.93327904 0.69267046]], shape=(3, 4), dtype=float32)


In [22]:
print(np.random.randint(-10,10,(3,4)))

[[ -2  -9  -9   3]
 [-10   2  -3   8]
 [  1   8   3  -8]]


In [23]:
print(torch.randint(-10,10,(3,4)))

tensor([[  1,   8,   0,  -2],
        [ -9, -10,  -9,   0],
        [ -3,  -7,  -4,   8]])


In [27]:
print(tf.random.uniform(shape = (3,4), minval = -10, maxval = 10,dtype=tf.int32))

tf.Tensor(
[[  4   3  -9  -7]
 [  4   9   0  -5]
 [-10   8   5 -10]], shape=(3, 4), dtype=int32)
