# Câu 1

In [14]:
import numpy as np
import torch
import tensorflow as tf

lst_1D = [num for num in range(1,11)]
print(lst_1D)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [15]:
arr_1D = np.array(lst_1D)
pt_1D = torch.tensor(lst_1D)
tf_1D = tf.constant(lst_1D)

In [18]:
print(f"np: {arr_1D}")
print(f"pytorch: {pt_1D}")
print("tensorflow:",tf_1D)

np: [ 1  2  3  4  5  6  7  8  9 10]
pytorch: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensorflow: tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int32)


# Câu 2

In [19]:
lst_2D = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

arr_2D = np.array(lst_2D)
pt_2D = torch.tensor(lst_2D)
tf_2D = tf.constant(lst_2D)

In [20]:
print(f"np: {arr_2D}")
print(f"pytorch: {pt_2D}")
print("tensorflow:",tf_2D)

np: [[1 2 3]
 [4 5 6]
 [7 8 9]]
pytorch: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensorflow: tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [23]:
print("Numpy: ")
print(f"shape: {arr_2D.shape}")
print(f"dtype: {arr_2D.dtype}")
print(f"type: {type(arr_2D)}\n")

print("Pytorch: ")
print(f"shape: {pt_2D.shape}")
print(f"dtype: {pt_2D.dtype}")
print(f"type: {type(pt_2D)}")
print(f"device: {pt_2D.device}\n")

print("Tensorflow: ")
print(f"shape: {tf_2D.shape}")
print(f"dtype: {tf_2D.dtype}")
print(f"type: {type(tf_2D)}")
print(f"device: {tf_2D.device}")

Numpy: 
shape: (3, 3)
dtype: int32
type: <class 'numpy.ndarray'>

Pytorch: 
shape: torch.Size([3, 3])
dtype: torch.int64
type: <class 'torch.Tensor'>
device: cpu

Tensorflow: 
shape: (3, 3)
dtype: <dtype: 'int32'>
type: <class 'tensorflow.python.framework.ops.EagerTensor'>
device: /job:localhost/replica:0/task:0/device:CPU:0
