In [1]:
import numpy as np
import torch
import tensorflow as tf

# Câu 1

In [2]:
print(np.zeros((3,4)))
print(torch.zeros((3,4)))
print(tf.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


# Câu 2

In [3]:
print(np.ones((3,4)))
print(torch.ones((3,4)))
print(tf.ones((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


# Câu 3

In [4]:
print(np.full((3,4),5))
print(torch.full((3,4),5))
print(tf.fill((3,4),5))

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])
tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)
